services:
  testing-postgres:
    image: docker.io/postgres:13.8-alpine3.16
    container_name: postgres
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
  testing-zabbix-server:
    image: docker.io/zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
  testing-zabbix-web:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    ports:
      - "4444:8080"
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Paris