name: Build cli

on:
  push:
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # - name: Build binaries [linux-adm64]
    #   run: make build-linux
    #   shell: bash

    - name: Build binaries
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --config build/goreleaser.yml --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Upload binaries
    #   uses: svenstaro/upload-release-action@2.4.0
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: dist/zabbix-tree-cli_*
    #     tag: ${{ github.ref }}
    #     overwrite: true
    #     file_glob: true