name: Build cli

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build binaries [linux-adm64]
      run: make build-linux
      shell: bash
    
    - name: Build binaries [windows-adm64]
      run: make build-windows
      shell: bash
    
    - name: Upload binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/zabbix-tree-cli*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true